name: Build and upload to PyPI

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      # We will need cibuildwheel if we add a cython extension for common beam calcs
      # - name: Install cibuildwheel
      #  run: python -m pip install cibuildwheel
      - name: Build wheels
        run: python -m pip wheel --wheel-dir=wheelhouse .
        # run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-*
          CIBW_TEST_EXTRAS: test
          CIBW_TEST_COMMAND: pytest --pyargs radio_beam
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist_and_wheel:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      - name: Install build
        run: python -m pip install build
      - name: Build sdist
        run: python -m build --sdist --wheel --outdir dist/ .
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*

  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
